### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by phenomax** [plentymarkets/plugin-elastic-export-geizhals-de#6]
When using this plugin - all export parameters are unchanged - an internal error occurs.
This happens, when calling the download action of the export .csv file

The whole instance is hosted on a cloud instance of PlentyMarkets v7.0.0 with only two plugins installed:
ElasticExports v1.2.5 & ElasticExportGeizhalsDE v1.0.4

![image](https://user-images.githubusercontent.com/12475496/29378667-34836cfa-82c0-11e7-852d-47a72d4550d7.png)

The download page just shows `Internal error`

**Comment by Desentyer** [comment]
Hello phenomax,

have you tried to update your Geizhals plugins? There is a newer version available and maybe it will solve your problem. 
If not, could you give me your plentymarkets System ID? (PID)

Best Regards
Marius

**Comment by phenomax** [comment]
Thanks!
Now everything is working as expected. Please note that I got the outdated version of this plugin right from your marketplace. 
I had to clone this repo in order to get the most recent version.

**Comment by alinmigea** [comment]
Hey @phenomax 

thanks for the feedback, it's appreciated.
I'll try to check again to see if this behaviour still happens. But at first sight it it seems that on the marketplace the version was revised and points now to the correct version v1.0.8.

Thanks again and please check further more to have the latest versions of your used plugins. 
Feel free to push us an issue, when you have another questions.

Kind regards,
Alin
